apiVersion: v1
kind: ConfigMap
metadata:
  name: gangway
  namespace: tanzu-system-auth
data:
  gangway.yaml: |
    serveTLS: false
    certFile: /tls/tls.crt
    keyFile: /tls/tls.key
    clusterName: tanzu
    authorizeURL: http://dex.auth.app.local:9480/auth
    tokenURL: http://dexsvc/token
    scopes:
    - openid
    - profile
    - email
    - offline_access
    redirectURL: http://dex.auth.app.local:9480/callback
    clientID: tanzu
    usernameClaim: email
    apiServerURL: https://127.0.0.1:9643/
    trustedCAPath: /etc/dex/dex-ca.crt
    idpCAPath: /etc/dex/dex-ca.crt
