apiVersion: v1
kind: ConfigMap
metadata:
  name: gangway
  namespace: tanzu-system-auth
data:
  gangway.yaml: |
    serveTLS: false
    certFile: /tls/tls.crt
    keyFile: /tls/tls.key
    clusterName: "bender"
    authorizeURL: "http://dex.auth.app.local:9480/auth"

    # OAuth2 URL to obtain access tokens.
    # Env var: GANGWAY_TOKEN_URL
    tokenURL: "http://dexsvc/token"

    # Endpoint that provides user profile information [optional]. Not all providers
    # will require this.
    # Env var: GANGWAY_AUDIENCE
    # audience:

    # Used to specify the scope of the requested Oauth authorization.
    scopes: ["openid", "profile", "email", "offline_access"]

    # Where to redirect back to. This should be a URL where gangway is reachable.
    # Typically this also needs to be registered as part of the oauth application
    # with the oAuth provider.
    # Env var: GANGWAY_REDIRECT_URL
    redirectURL: "http://gangway.auth.app.local:9480/callback"

    # API client ID as indicated by the identity provider
    # Env var: GANGWAY_CLIENT_ID
    clientID: "bender"

    # Some identity providers accept an empty client secret, this
    # is not generally considered a good idea. If you have to use an
    # empty secret and accept the risks that come with that then you can
    # set this to true.
    #allowEmptyClientSecret: false

    # The JWT claim to use as the username. This is used in UI.
    # Default is "nickname". This is combined with the clusterName
    # for the "user" portion of the kubeconfig.
    # Env var: GANGWAY_USERNAME_CLAIM
    usernameClaim: "email"

    # The API server endpoint used to configure kubectl
    # Env var: GANGWAY_APISERVER_URL
    apiServerURL: "https://127.0.0.1:9643/"

    # The path to find the CA bundle for the API server. Used to configure kubectl.
    # This is typically mounted into the default location for workloads running on
    # a Kubernetes cluster and doesn't need to be set.
    # Env var: GANGWAY_CLUSTER_CA_PATH
    # cluster_ca_path: "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"

    # The path to a root CA to trust for self signed certificates at the Oauth2 URLs
    # Env var: GANGWAY_TRUSTED_CA_PATH
    trustedCAPath: /etc/dex/dex-ca.crt

    # The path gangway uses to create urls (defaults to "")
    # Env var: GANGWAY_HTTP_PATH
    #httpPath: "https://${GANGWAY_HTTP_PATH}"

    # The path to find custom HTML templates
    # Env var: GANGWAY_CUSTOM_HTTP_TEMPLATES_DIR
    #customHTMLTemplatesDir: /custom-templates

    idpCAPath: /etc/dex/dex-ca.crt
