apiVersion: v1
kind: Secret
metadata:
  name: gangway
  namespace: tanzu-system-auth
type: Opaque
data:
  sesssionKey: EoIhzMf4QAyeBQnop3iLHqzENV+A+KPRSanHZdJ0OQM=
  clientSecret: dGFuenUtc2VjdXJpdHk=
