apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: gangway-ca-issuer
  namespace: tanzu-system-auth
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: gangway-cert
  namespace: tanzu-system-auth
spec:
  secretName: gangway-cert-tls
  duration: 2160h
  renewBefore: 360h
  organization:
  - vmware
  commonName: tkg-gangway
  isCA: false
  keySize: 2048
  keyAlgorithm: rsa
  keyEncoding: pkcs1
  dnsNames:
  - tkg-gangway
  - gangway.auth.app.local
  issuerRef:
    name: gangway-ca-issuer
    kind: Issuer
    group: cert-manager.io
