apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: dex-ca-issuer
  namespace: tanzu-system-auth
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: dex-cert
  namespace: tanzu-system-auth
spec:
  secretName: dex-cert-tls
  duration: 2160h
  renewBefore: 360h
  organization:
  - vmware
  commonName: tkg-dex
  isCA: false
  keySize: 2048
  keyAlgorithm: rsa
  keyEncoding: pkcs1
  dnsNames:
  - tkg-dex.com
  - dex.auth.app.local
  issuerRef:
    name: dex-ca-issuer
    kind: Issuer
    group: cert-manager.io
