apiVersion: v1
kind: ConfigMap
metadata:
  name: dex
  namespace: tanzu-system-auth
data:
  config.yaml: |
    issuer: http://dex.auth.app.local:9480
    frontend:
      theme: tkg
    web:
      http: 0.0.0.0:5556
      tlsCert: /etc/dex/tls/tls.crt
      tlsKey: /etc/dex/tls/tls.key
    expiry:
      signingKeys: 10m
      idTokens: 5m
    logger:
      level: debug
      format: json
    staticClients:
    - id: tanzu
      redirectURIs:
      - http://gangway.auth.app.local:9480/callback
      name: tanzu
      secret: tanzu-security
    connectors:
    - type: mockCallback
      id: mock
      name: Example
    - type: ldap
      name: OpenLDAP
      id: ldap
      config:
        host: ldapsvc:389
        insecureNoSSL: true
        bindDN: cn=admin,dc=example,dc=org
        bindPW: admin
        usernamePrompt: Email Address
        userSearch:
          baseDN: ou=People,dc=example,dc=org
          filter: (objectClass=person)
          username: mail
          idAttr: DN
          emailAttr: mail
          nameAttr: cn
        groupSearch:
          baseDN: ou=Groups,dc=example,dc=org
          filter: (objectClass=groupOfNames)
          userMatchers:
          - userAttr: DN
          groupAttr: member
          nameAttr: cn
    oauth2:
      skipApprovalScreen: true
      responseTypes:
      - code
      - token
      - id_token
    storage:
      type: kubernetes
      config:
        inCluster: true
    enablePasswordDB: false
