#@ load("@ytt:data", "data")
apiVersion: v1
kind: Secret
metadata:
  name: gangway
  namespace: tanzu-system-auth
type: Opaque
data:
  #! openssl rand -base64 32 | pbcopy
  sesssionKey: EoIhzMf4QAyeBQnop3iLHqzENV+A+KPRSanHZdJ0OQM=
  #! clientSecret=$(openssl rand -base64 32)
  #! echo -n "$clientSecret" | base64
  clientSecret: #@ data.values.static.client.encoded

